name: Backend Pull Request

on:
  pull_request:
    branches:
      - '*'

jobs:

  git-leaks-check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.before }}
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Git Leaks Check
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  codestyle-check-java:
    needs: git-leaks-check
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  markdown-files-check:
    needs: git-leaks-check
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # run on 18 as version 12 is deprecated and version 16 is unsupported for markdownlint-cli

      - name: Install Markdown Lint And Check Markdown Files
        run: npm install -g markdownlint-cli && markdownlint '**/*.md'

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  build:
    needs: [ git-leaks-check, codestyle-check-java]
    runs-on: ubuntu-latest

    outputs:
      id: jar
      settable: true
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package
          echo "::set-output name=jar::target/travelly.jar"

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  test:
    needs: build
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Unit and Integration Tests
        run: |
          # Use the JAR file produced by the 'build' job
          echo "Running tests using ${{ needs.build.outputs.jar }}"
          
          # Example: Run JUnit tests
          mvn test

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  sonar:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: SonarQube Scan
        run: mvn clean verify sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  snyk-check:
    needs: test
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set-status.outputs.status }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Snyk
        uses: snyk/actions/setup@master

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # run on 16 as version 12 is deprecated

      - name: Snyk Monitor
        run: snyk auth ${{ secrets.SNYK_TOKEN }} && snyk test --severity-threshold=high

      - name: Set Status
        id: set-status
        run: echo "::set-output name=status::${{ job.status }}"


  slack-notify:
    needs: [ git-leaks-check, codestyle-check-java, markdown-files-check, build, test, sonar, snyk-check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: pipelines
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: |
            Pull Request Status:
            - Git Leaks Check: ${{ needs.git-leaks-check.outputs.status }}
            - Codestyle Check: ${{ needs.codestyle-check-java.outputs.status }}
            - Markdown Files Check: ${{ needs.markdown-files-check.outputs.status }}
            - Build: ${{ needs.build.outputs.status }}
            - Tests: ${{ needs.test.outputs.status }}
            - Static Code Analysis: ${{ needs.sonar.outputs.status }}
            - Dependency Scanning: ${{ needs.snyk-check.outputs.status }}
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  jira-transition:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Jira Transition
        run: |
          # Extract Jira issue key from the pull request title
          JIRA_ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'DEV-\d+')
          echo "Jira Issue Key: $JIRA_ISSUE_KEY"
          
          # Jira Transition URL
          JIRA_TRANSITION_URL="${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${JIRA_ISSUE_KEY}/transitions"
          
          # Jira Transition ID for "In Review" status (update this based on your Jira workflow)
          JIRA_TRANSITION_ID="pr-made"
          
          # Jira API Username and Token
          JIRA_API_USERNAME="${{ secrets.JIRA_USERNAME }}"
          JIRA_API_TOKEN="${{ secrets.JIRA_API_TOKEN }}"
                  
          # Get the transition ID for the specified transition name
          JIRA_TRANSITION_ID=$(curl -u "$JIRA_API_USERNAME:$JIRA_API_TOKEN" -X GET -H "Content-Type: application/json" "$JIRA_TRANSITION_URL" | jq -r --arg name "$JIRA_TRANSITION_NAME" '.transitions[] | select(.name == $name) | .id')
          echo "Jira Transition ID: $JIRA_TRANSITION_ID"
          
          # Make the Jira API request to transition the issue
          curl -X POST \
            --url "$JIRA_TRANSITION_URL" \
            --user "$JIRA_API_USERNAME:$JIRA_API_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "'"$JIRA_TRANSITION_ID"'"}}'